name: Robot Framework API Test

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron:  '0 21 * * *'

jobs:
  run-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Test with robot
      run: |
        robot -d ./reports tests/tests.robot
    - name: Reporting
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Reports
        path: reports
